site_name: ABCI Portal Guide
site_description: AI Bridging Cloud Infrastructure(ABCI)
site_author: AIST
site_url: https://portal.abci.ai/docs/portal/en/
copyright: 'Copyright &copy; 2018 National Institute of Advanced Industrial Science and Technology(AIST)'
google_analytics: ['UA-118371652-2', 'portal.abci.ai']
pages:
  - 'Introduction': 'index.md'
  - '1. New Registration': '01.md'
  - '2. User Portal': '02.md'
  - '3. User Management Authority': '03.md'
theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'blue'
markdown_extensions:
  - admonition
  - codehilite:
