site_name: ABCI Users Guide
site_description: AI Bridging Cloud Infrastructure (ABCI)
site_author: AIST
site_url: https://docs.abci.ai/
repo_url: https://github.com/aistairc/abci-docs
edit_uri: edit/master/root/docs/
copyright: 'Copyright &copy; 2018 National Institute of Advanced Industrial Science and Technology (AIST)'
google_analytics: ['UA-118371652-2', 'portal.abci.ai']
nav:
  - 'Welcome': 'index.md'
  - 'Privacy Policy': 'privacy-policy.md'
theme:
  name: 'material'
  palette:
    primary: 'red'
    accent: 'red'
  feature:
    tabs: false
markdown_extensions:
  - admonition
  - codehilite
